name: IoT Lab CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install flake8
        
    - name: Lint BT1
      run: flake8 BT1_QEMU_SystemMonitor/ --max-line-length=120 --show-source || true
      
    - name: Lint BT2
      run: flake8 BT2_QEMU_SensorSim/ --max-line-length=120 --show-source || true
      
    - name: Check file structure
      run: |
        echo "Kiem tra cau truc thu muc"
        ls -la
        echo "Structure OK"
